#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

#https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy.html

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides VpcId="vpc-0a991491df38184c6" WebServerSGGroupId="sg-05012f266398162f7" Subnets="subnet-0b81501bf23d02e01,subnet-0defd44cfa784b0d3,subnet-076c3393cafbf6914" \
--region af-south-1 \
--stack-name $STACK_NAME