#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

#https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy.html

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides VpcId="vpc-08abc17831219be24" WebServerSGGroupId="sg-0f11dcae0e77d76f6" Subnets="subnet-020a9415b2acbfe86,subnet-0e64ad2b62255b780,subnet-0be3e3f11218afc48,subnet-01cf99e6be4894259" \
--region af-south-1 \
--stack-name $STACK_NAME